[package]
name = "actix-jwt-auth-middleware-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.10"
syn = {version = "1.0", features = ["extra-traits"]}

[lib]
proc-macro = true